# Enable React Native New Architecture
ENV['RCT_NEW_ARCH_ENABLED'] = '1'

require Pod::Executable.execute_command(
  'node',
  [
    '-p',
    'require.resolve(
      "react-native/scripts/react_native_pods.rb",
      { paths: [process.argv[1]] },
    )',
    __dir__
  ]
).strip

platform :ios, '15.1'

prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pods with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'CrypWise' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => true,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Example: Add additional pods here if needed

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end
end