import { StyleSheet } from "react-native";
import { CWTypography } from "./CWTextType";


export const useTypography = (token: CWTypography) => {
  return textStyle[token];
};

const textStyle = StyleSheet.create({
  heading_xl: {
    fontFamily: "JioType-Black",
    fontSize: 64,
    fontWeight:'700',
    lineHeight: 64,
    letterSpacing: -0.72,
  },
  heading_l: {
    fontFamily: "JioType-Black",
    fontWeight:'700',
    fontSize: 48,
    lineHeight: 48,
    letterSpacing: -0.72,
  },
  heading_m: {
    fontFamily: "JioType-Black",
    fontWeight:'700',
    fontSize: 40,
    lineHeight: 40,
    letterSpacing: -0.72,
  },
  heading_s: {
    fontFamily: "JioType-Black",
    fontWeight:'700',
    fontSize: 32,
    lineHeight: 32,
    letterSpacing: -0.72,
  },
  heading_xs: {
    fontFamily: "JioType-Black",
    fontWeight:'700',
    fontSize: 24,
    lineHeight: 28,
    letterSpacing: -0.72,
  },
  heading_xxs: {
    fontFamily: "JioType-Black",
    fontWeight:'700',
    fontSize: 16,
    lineHeight: 20,
    letterSpacing: -0.72,
  },
  overline: {
    fontFamily: "JioType-Bold",
    fontWeight:'700',
    fontSize: 14,
    lineHeight: 16,
    letterSpacing: -0.12,
  },
  body_l: {
    fontFamily: "JioType-Medium",
    fontWeight:'500',
    fontSize: 24,
    lineHeight: 32,
    letterSpacing: -0.12,
  },
  body_l_bold: {
    fontFamily: "JioType-Bold",
    fontWeight:'700',
    fontSize: 24,
    lineHeight: 32,
    letterSpacing: -0.12,
  },
  body_l_link: {
    fontFamily: "JioType-Bold",
    fontWeight:'700',
    fontSize: 24,
    lineHeight: 32,
    letterSpacing: -0.12,
  },
  body_m: {
    fontFamily: "JioType-Medium",
    fontWeight:'500',
    fontSize: 18,
    lineHeight: 24,
    letterSpacing: -0.12,
  },
  body_m_bold: {
    fontFamily: "JioType-Bold",
    fontWeight:'500',
    fontSize: 18,
    lineHeight: 24,
    letterSpacing: -0.12,
  },
  body_m_link: {
    fontFamily: "JioType-Bold",
    fontWeight:'500',
    fontSize: 18,
    lineHeight: 24,
    letterSpacing: -0.12,
  },
  body_s: {
    fontFamily: "JioType-Medium",
    fontWeight:'500',
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: -0.12,
  },
  body_s_bold: {
    fontFamily: "JioType-Bold",
    fontWeight:'500',
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: -0.12,
  },
  body_s_link: {
    fontFamily: "JioType-Bold",
    fontWeight:'500',
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: -0.12,
  },
  body_xs: {
    fontFamily: "JioType-Medium",
    fontWeight:'500',
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: -0.12,
  },
  body_xs_bold: {
    fontFamily: "JioType-Bold",
    fontWeight:'700',
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: -0.12,
  },
  body_xs_link: {
    fontFamily: "JioType-Bold",
    fontWeight:'500',
    fontSize: 14,
    lineHeight: 16,
    letterSpacing: -0.12,
  },
  body_xxs: {
    fontFamily: "JioType-Medium",
    fontWeight:'500',
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: -0.12,
  },
  body_xxs_bold: {
    fontFamily: "JioType-Bold",
    fontWeight:'500',
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: -0.12,
  },
  body_xxs_link: {
    fontFamily: "JioType-Bold",
    fontWeight:'500',
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: -0.12,
  },
  button: {
    fontFamily: "JioType-Bold",
    fontWeight:'500',
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: -0.12,
  },
  body_3xs:{
    fontFamily:"JioType-Medium",
    fontSize:11,
    lineHeight:14,
    letterSpacing:-0.12,
  },
  body_3xs_bold:{
    fontFamily:"JioType-Bold",
    fontSize:11,
    lineHeight:14,
    letterSpacing:-0.12,
  },
  body_3xs_link:{
    fontFamily:"JioType-Bold",
    fontSize:11,
    lineHeight:14,
    letterSpacing:-0.12,
  },
});
